### ISSUE TITLE
Option to ♡ currently playing track

### ISSUE THREAD

**Issue by jakezien** [DimitarNestorov/MusicBar#9] opened 2021-03-22 23:27 UTC
This is the feature that no menubar remote currently supports, and the one action I consistently find myself wanting to take without interrupting whatever I'm doing. Both Spotify and Apple Music have some kind of Heart/Love/Thumbs Up feature; would be an awesome addition to the controls overlay in the popup. 

Killer app; thanks so much for your great dev work!

**Comment by jakezien** [comment] 2021-04-05 23:55
Note: this issue is a feature request; would add the label myself if GitHub would let me.
Edit: looks like this is basically the same thing as #3. Two more 👍 for that request, then!

**Comment by DimitarNestorov** [comment] 2021-06-01 14:38
Closing since it's a duplicate of #3 and I would prefer to keep issues as few as possible. But that issue never mentioned Spotify, so I'm going to add it as a tag to remind me when I work on it.

**Closed as completed by DimitarNestorov** 2021-06-01 14:38 UTC
Labels: feature request, duplicate
